### ISSUE TITLE
Scrollbar in the middle of the screen.

### ISSUE THREAD

**Issue by DevFranPR** [MiyooCFW/gmenu2x#11]
Just bought a Powkiddy v90 one month ago and replace the SD for a brand new one. At first it worked nicely but someday appeared a straight line across the screen. My first thought some kind of hardware error but in the scrollable UIs it seems to be the scroll bar or change with it. I tried to move it to the side of the screen in the options and search for solutions on the internet but can't find a solution. Looks like a stupid request but this line keeps when open the games and buggs the hell out of me. Can someone help me with this?
![photo](https://user-images.githubusercontent.com/50636975/149680041-3fe40c9f-5192-4238-8037-60661ed864c3.jpg)
.

**Comment by TriForceX** [comment]
It happens only on that skin/theme?

**Comment by DevFranPR** [comment]
It happens in all themes. Maybe is a screen error but the screen is new and it appears to show color changes on the scrolling (?) I don't know exactly if is a hardware or software problem. I just ask in case of a software problem, there isn't to much info on the internet about this kind of error.

**Comment by Apaczer** [comment]
can't reproduce, you might try to update your gmenu2x or see if this happens on another device.
