### ISSUE TITLE
Replace British English "favourite" with U.S. English "favorite"

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#50]
Since the Project's README.md states that the main language is U.S. English then it would be appropriate to replace British English "favourite" with U.S. English "favorite".
https://www.merriam-webster.com/grammar/favorite-or-favourite-usage
Currently in the interface this word appears as the title of a "favourites" section and as one of the menu entries - "Add to Favourites".

**Comment by Apaczer** [comment]
Right, the favourite resonated more with me, probably cuz I'm from Europe. Fixed with: https://github.com/MiyooCFW/gmenu2x/commit/266f24eb61dd4eb12d3a2739d8f997cabd06c71e
