### ISSUE TITLE
Hastily made plugs of new section icons for the theme NewComicBook

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#54]
Hastily made plugs of new, not originally intended section icons (Cores and Favorites) for the theme NewComicBook:

![ncbf](https://github.com/MiyooCFW/gmenu2x/assets/43220515/1a5dd5b8-6859-4ecc-850d-942bad6604e0)

Images used from the same set [Yoshi-kun_theme-2017-01-25](https://forums.libretro.com/t/yoshi-kun-icons-theme/8371).
https://yspixel.jpn.org/icon/game/index.htm
Was done quickly, but it's still better than an automatic plugs.

![cores](https://github.com/MiyooCFW/gmenu2x/assets/43220515/00b9c62b-4a11-4673-b1b2-cc0be0d8a7ee)
![cores](https://github.com/MiyooCFW/gmenu2x/assets/43220515/6ac8d5a3-970e-40aa-97be-9d434df584a3)

![favorites](https://github.com/MiyooCFW/gmenu2x/assets/43220515/a0152243-900e-4175-9445-6091fe59a13b)
![favorites](https://github.com/MiyooCFW/gmenu2x/assets/43220515/7132d37b-bb74-44ad-b80c-25fd769cb29e)

**Comment by Apaczer** [comment]
Thanks @MayanKoyote will add it to assets soon, also investigating other issues.

**Comment by MayanKoyote** [comment]
In the end it turned out to be irrelevant, theme's license restrictions (CC-BY-NC-ND 4.0) ruins everything.
