### ISSUE TITLE
[FR] Make the about.txt file multilingual and translatable.

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#55]
[Feature Request] Make the about.txt file multilingual and translatable.

I remember that I already suggested this in discord once, but I will repeat it here:
Why not make the file https://github.com/MiyooCFW/gmenu2x/blob/master/about.txt multilingual and translatable?
And make it so that, depending on the set language of GMenu2X, when user click on the “About” link, a localized version of this file would be displayed (and if there is no such localized file, then the English version of the file would be displayed).
I consider this necessary because the file contains useful information about the hot keys used in the menu. Essentially this is a short guide.
Yes, I know that no one ever reads instructions. But it won't be completely useless.

Something similar can be seen here, for example:
https://github.com/Fledge68/WiiFlow_Lite/tree/master/wii/wiiflow/help

**Comment by Apaczer** [comment]
added and cleaned "about" to only include mostly "Controls" for now. Thanks for suggestion!
