### ISSUE TITLE
[FR] In the Default theme (and Nsdark theme), replace the Bebas Kai font with the Bebas Neue Bold (2014) font to add support for Cyrillic (Russian) characters.

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#56]
[Feature Request] In the Default theme, replace the Bebas Kai font with the Bebas Neue Bold (2014) font to add support for Cyrillic (Russian) characters.

The Default theme currently uses the Bebas Kai font. Version 1.002. This font has 429 glyphs. This font does not support Cyrillic (Russian) characters:
![cyrr01](https://github.com/MiyooCFW/gmenu2x/assets/43220515/c38809e0-ce9c-4563-abd1-08648c1fe8df)

The same author has the Bebas Neue Family (2014) font family and specifically the Bebas Neue Bold font. Version 1.003.
This font has an almost identical style. This font has 486 glyphs. The main difference is the presence of Cyrillic (Russian) characters:
![cyrr02](https://github.com/MiyooCFW/gmenu2x/assets/43220515/524b8270-d020-41db-bdac-d1d0ff138cd5)

This font is also licensed under the SIL Open Font License, Version 1.1.

The appearance of Cyrillic (Russian) characters in the Default theme font, in my opinion, would not be unnecessary.
At the same time, the overall appearance and style of the theme does not suffer:
![eng](https://github.com/MiyooCFW/gmenu2x/assets/43220515/7da1517b-0991-40d1-aae3-6adbc95ea868)

Yes, this does not solve the problem of the lack of many other characters (Greek or CJK characters, for example), but it is better than nothing.

Link to the font author's repository:
https://github.com/dharmatype/Bebas-Neue
Link to the Bebas Neue Family (2014)
https://github.com/dharmatype/Bebas-Neue/tree/master/fonts/BebasNeue(2014)ByFontFabric
And link specifically to the font itself:
https://github.com/dharmatype/Bebas-Neue/raw/master/fonts/BebasNeue(2014)ByFontFabric/BebasNeue-Bold.ttf

**Comment by MayanKoyote** [comment]
By the way, Bebas Kai font is also used in the "Nsdark" theme:
![cyrr-nsd](https://github.com/MiyooCFW/gmenu2x/assets/43220515/919bdd59-888b-450d-8e52-0f6ed6f7469c)
![eng-nsd](https://github.com/MiyooCFW/gmenu2x/assets/43220515/b151cf3f-6b2d-46c6-ac2f-74db74f69ef6)

It would be good to change it to Bebas Neue Bold (2014) font too for the same reasons.

**Comment by Apaczer** [comment]
@MayanKoyote I liked your idea to update default font, but the tracking (kerning?) of the Neue Bold is clearly more narrow. However I've used `fontmerge` app to do some Frankestein job and mixed Bebas fonts with GNU_Unifont in such order: BebasKai->BebasNeueBold->GNU_Unifont. That way all characters in BebasKai will be untouched but will also receive new characters from BebasNeueBold + additionaly missing ones form GNU_Unifont.

**Comment by Apaczer** [comment]
tested with:
    <details>
        <summary> text_cjk.txt </summary>
       こんにちは世界
你好世界
안녕 세계
مرحبا بالعالم
ନମସ୍କାର ବିଶ୍ୱବାସି
Γειά σου Κόσμε
    </details>
[test_cjk.txt](https://github.com/MiyooCFW/gmenu2x/files/14068662/test_cjk.txt)
