### ISSUE TITLE
In the 'GameShow' theme, when editing, the names of the actions that can be performed using the buttons are not visible.

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#62]
In the 'GameShow' theme, when editing, the names of the actions that can be performed using the buttons (in the bottom line for buttons: B ST Y L R) are not visible:
![gstnv](https://github.com/MiyooCFW/gmenu2x/assets/43220515/2abd0670-abe8-414f-bd00-76cdd6f19bcf)
(fresh install, no fiddling with settings, only the theme has been switched)

**Comment by Apaczer** [comment]
currently:
![obraz](https://github.com/MiyooCFW/gmenu2x/assets/94932128/90067c42-ecff-4a7f-9a50-5c827706f602)
