### ISSUE TITLE
[Q] Is it possible to use screen space more efficiently to display settings and messages?

### ISSUE THREAD

**Issue by MayanKoyote** [MiyooCFW/gmenu2x#63]
Is it possible to use screen space more efficiently to display settings and messages?

1. In the settings (any, perhaps with the exception of the "Skin Colors" sub-settings), is it possible to divide the screen not 50%-50% for a variable name and its value, but 60%-40% (or something)?
What is this for: on the left side we are constantly trying to stuff in almost the whole “The quick brown fox jumps over the lazy dog” comparable amount of text, on the right side we usually have something like “OFF”, “12”, “AUTO”, etc. ( the longest value here is probably the name of the wallpaper).

2. Can messages (especially 'hint' messages) be two-line (auto split or with help of \n symbol manually inserted into the text of the message) rather than single-line?
What is this for: well, same. Often the text is quite long and tends to extend beyond the screen in both directions.

**Comment by Apaczer** [comment]
1) Agree, made a little correction (date&time untouched to save us of crossed eyes):
![screenshot](https://github.com/MiyooCFW/gmenu2x/assets/94932128/14a75ac5-b3a2-4852-8322-68ae9c2fedf8)

2) Now for msgbox'es you have to manually insert \n char in code, but strings with special char sequences are untraslatable (that may need fixing if possible). I don't trust (understand?) font wrapping in gmenu2x, so wouldn't rely on auto-splitting of text. So maybe by adding proper reading of '\n' in Translator class...

**Comment by MayanKoyote** [comment]
I definitely like it.
