### ISSUE TITLE
Extended "main" on v90 fw..but

### ISSUE THREAD

**Issue by tobiibr** [MiyooCFW/gmenu2x#9]
Hi, I have extended "main" on v90 fw but when I paste game files it sais there is no space. On Linux disk manager i see that I extended it on 60gb. What to do now? But at device card works good even with miyoo

**Comment by TriForceX** [comment]
Whats your sd card capacity?

**Comment by tobiibr** [comment]
64gb. I send screenshot of parts later.

**Comment by tobiibr** [comment]
![16382673371288783651397340122479](https://user-images.githubusercontent.com/95256718/144028741-ac2874e6-7ffd-410d-8808-983dc99ef586.jpg)

**Comment by szymor** [comment]
You need to resize not only the partition, but the file system on it as well.
